version: '3'
services:
  db:
    image: postgres:11.11
    volumes:
      - db-data:/var/lib/postgresql/data:cached
  app:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb"
    volumes:
      - .:/best-lab:cached
      - bundle-data:/usr/local/bundle:cached
      - log-data:/best-lab/log
      - public-data:/best-lab/public:cached
      - tmp-data:/best-lab/tmp:cached
    tty: true
    links:
      - db
  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - public-data:/best-lab/public
      - tmp-data:/best-lab/tmp:cached
    ports:
      - '80:80'
    links:
      - app

volumes:
  bundle-data:
  db-data:
  log-data:
  tmp-data:
  public-data:
